### ISSUE TITLE
"./manage.py migrate" required at the first launch

### ISSUE THREAD

**Issue by MikaXII** [recalbox/recalbox-manager#12]
Can override this ?

**Comment by sveetch** [comment]
Yes, i would want to definitively avoid database usage, so this would not be needed.

But in fact, this we can do without, will just have to ship the dummy database created (db.sqlite3) on your install or my development install, because finally the webapp does not really use datas from the db so we don't care of dummy datas. Just need the file and Django won't say nothing about syncdb or migrate requirements.

**Comment by sveetch** [comment]
Ok i noted it in the README, but will have to tell about to ship the db.sqlite3 file into the recalbox manager package so the server will be totally ready to run.
