### ISSUE TITLE
Icon on navigation bar redirect to "example.com"

### ISSUE THREAD

**Issue by MikaXII** [recalbox/recalbox-manager#13]

**Comment by sveetch** [comment]
Actually this is the link from a common django app called "Site framework" that is filled to this domain by default.

I plan to remove it's usage, since we have to display the recalbox IP, so i have to find the right IP before.

**Comment by sveetch** [comment]
Easy fix removing the host and just use the "/"

Will see in another task issue to find the recalbox IP and use it.

**Comment by MikaXII** [comment]
I'm redirect to port 8001, and I launch reunserver 0.0.0.0:3000.
But in recalbox default port must be 80.

**Comment by sveetch** [comment]
Since last commit, now there is a setting to set some "site" infos like name, hostname (ip) and port.

I don't know if there is a right way to find the used port for the django instance, maybe i will have to dig in code to find this. Until i find it (or not), set the port you use in settings.SITE_FIXED on the 'port' item.

For next commit to come i will add a settings_production (assuming the rpi is the production target) where i will set the port to 80 (it can't be used in default nor development setting environment because the port 80 is often already used on many server).

**Comment by sveetch** [comment]
Re opening this until i add the settings_production with port 80 setted.
