### ISSUE TITLE
Upload multi-files

### ISSUE THREAD

**Issue by MikaXII** [recalbox/recalbox-manager#15]

**Comment by digitalLumberjack** [comment]
@Required for the integration in recalbox

**Comment by sveetch** [comment]
Is this really REQUIRED for a first release ?

I'm not again this feature, indeed i watched for solutions to integrate when i started the webapp. But didn't find a great Django app ready to work and with a good JS library. I finded somes, but didn't have time to test it.

Also, this will have to be checked for memory usage, as all uploaded file in the same request will be temporary save in memory until accepted/rejected.

**Comment by sveetch** [comment]
Oh and by the way, i have to do issue #2 before i mind about multiple upload.

**Comment by digitalLumberjack** [comment]
Yes it is really required. My 3358 snes roms would be a pain to upload one by one.

**Comment by sveetch** [comment]
Just to let you know this is on the way, i succeeded to use Dropzone Javascript, it works fine but i have to do a lot of integration to do it right. May take a week before i finish on my extra hours :)

**Comment by sveetch** [comment]
A note: I didn't put any limit. This will potentially lead to problems on a Recalbox.

I think the raspberry won't handle nice the charge of uploading rom files size for more than 200Mo each. Also, i think upload too many files ~50 could cause some issues (depending on file size).

Take in mind that each file will open a new request (one by one, i didnt enabled the parallel uploads) to do some validation about file.

Finally i didn't put any limits because i don't know yet the real usage of this from users. But it should be a great idea to talk about this and choose some limits before releasing into Recalbox.

**Comment by digitalLumberjack** [comment]
tu peux pas mettre les requetes en queue ?

**Comment by digitalLumberjack** [comment]
oué j'avais la flemme d'ecrire en anglais

**Comment by sveetch** [comment]
Uploads are allready in queue, since i did not enabled parallel uploads, so upload request are made one after one when file are dragged in (or added from file browser).

But think about the instance memory should grow a little since it won't have time to totally recover after each upload request. But this may not really affect a long time; the instance should recover a little time at the end.

**Comment by digitalLumberjack** [comment]
that's good for me

**Comment by sveetch** [comment]
Ok but don't complain if they are users crying their filesystem has gone in the space after dragging 120 GBA roms in a one shot and this leaded to crash :)

**Comment by MikaXII** [comment]
Désolé je fais FR également :

"Ok but don't complain if they are users crying their filesystem has gone in the space after dragging 120 GBA roms in a one shot and this leaded to crash :)"

Je te met au défis d'uploader 120 Roms une à une sans pleurer ^^...

---

De : David THENON notifications@github.com
Envoyé : mardi 6 octobre 2015 19:55
À : sveetch/recalbox-manager
Cc : JOUBERT Mikael
Objet : Re: [recalbox-manager] Upload multi-files (#15)

Ok but don't complain if they are users crying their filesystem has gone in the space after dragging 120 GBA roms in a one shot and this leaded to crash :)

## 

Reply to this email directly or view it on GitHubhttps://github.com/sveetch/recalbox-manager/issues/15#issuecomment-145946074.

[https://avatars0.githubusercontent.com/u/5852233?v=3&s=400]https://github.com/sveetch/recalbox-manager/issues/15#issuecomment-145946074

Upload multi-files · Issue #15 · sveetch/recalbox-manager ...
recalbox-manager - Django project to manage a Recalbox from a web interface
Lire la suite...https://github.com/sveetch/recalbox-manager/issues/15#issuecomment-145946074

**Comment by sveetch** [comment]
Ok it's done since release 1.0.0 (commit 6ee597a) but i'm not confident about the Dropzone widget integration.

I close this issue, but the work will continue on issue #28
