### ISSUE TITLE
Default recalbox-manager's port in recalbox

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-manager#30]
Hi, in recalbox, recalbox-manager will be automatically started on the 80 port.
So when I 'm trying to click on the recalbox-manager icon on top of the screen, I'm redirected to `http://XX.XX.XX.XX:8001/`.

**Comment by sveetch** [comment]
This is because you are not using the right settings file for production like you can see it there https://github.com/sveetch/recalbox-manager#notes-for-production

Default settings is only a "base", with production settings the configured port is "80" (in fact there is a blank port definition, so obviously in http it will rely on port 80).

Let me know if it resolves your issue.
