### ISSUE TITLE
Extension checks for roms

### ISSUE THREAD

**Issue by MaxCorpEnjoy** [recalbox/recalbox-manager#46]
It seems like, only a few extensions are allowed to pass through the uploader.
My GBA roms are zipped (and I guess only *.gba are allowed) and the *.bin were blocked for the Atari2600.
Not sure if there are other missing extensions somewhere else, but I guess it's not so tough to extend the list for each system.

**Comment by sveetch** [comment]
@rockaddicted has pulled some changes to add zip extension support for some system, you can see its changes on https://github.com/recalbox/recalbox-manager/pull/44/files

All in all, Recalbox should include the Manifest so i dont have to manage it myself, because i dont really follow the systems news, better to talk with @rockaddicted or @digitalLumberjack about extension support, as i won't add support myself without their acknowledgement

**Comment by sveetch** [comment]
Ok 'bin' extension support has been confirmed and added to the manifest to come in 1.1.5, 'zip' extension support for GBA has allready been added by @rockaddicted in its pull request.
